name: decoder
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter_vibrate: ^1.0.2
  matrix: ^0.20.5
  package_info_plus: ^4.0.2
  provider: ^6.0.5
  dynamic_color: ^1.6.5
  flutter_app_lock: ^3.0.0
  go_router: ^7.1.1
  shared_preferences: ^2.1.2
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  native_imaging: ^0.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  adaptive_dialog: ^1.9.0-0
  url_launcher: ^6.1.11
  future_loading_dialog: ^0.2.4
  google_fonts: ^4.0.4
  file_picker: ^5.3.1
  adaptive_action_sheet: ^2.0.2
  desktop_notifications: ^0.6.3
  desktop_lifecycle: ^0.1.1
  font_awesome_flutter: 10.1.0
  auto_size_text: 3.0.0
  from_css_color: 2.0.0
  json_path: 0.4.1
  timeago: 3.2.2
  page_transition: 2.0.4


  image_picker: ^1.0.0
  flutter_web_auth_2: ^2.1.5
  flutter_local_notifications: ^15.0.0
  unifiedpush: ^5.0.0
  vrouter: ^1.2.1
  flutter_cache_manager: ^3.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/chat_list/images/tabler_search.svg
    - assets/chat_list/images/user-buttom.png
    - assets/chat_list/images/pepicons-pencil_dots-y.svg
    - assets/chat_list/images/write.svg
    - assets/chat_list/images/prostors.svg
    - assets/fonts/
    - assets/icon/


